
def error(e: Exception):
    print("error")
    print(e)
